@startuml
' skinparam responseMessageBelowArrow true
title can apply a bunch of commands
group CreatePendingTask
  NotFound -> PendingTask : ScheduledTaskWorkflowCreated"

end
group StartTask
  PendingTask -> ExecutingTask : TaskStarted"

end
group RecordTaskSuccessAndComplete
  ExecutingTask -> CompleteTask : TaskCompleted"

end
@enduml